In [1]:
import numpy as np

This notebook demonstrates various NumPy array slicing and indexing techniques, including basic indexing, slicing, boolean indexing, fancy indexing, and conditional selection.

In [2]:
# Create a 10x10 array with values from 0 to 99
arr = np.array(range(100)) # Create a numpy array with values from 0 to 99
print(arr)
arr1 = arr.reshape((10,10)) # Reshape the array to 10x10
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [4]:
# Create a 10x10 array with values from 0 to 99
arr = np.array(range(90)) # Create a numpy array with values from 0 to 99
print(arr)
arr1 = arr.reshape((10,10)) # Reshape the array to 10x10
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89]


ValueError: cannot reshape array of size 90 into shape (10,10)

### select an element by row and column indices

In [7]:
arr = np.array(range(100)).reshape((10,10)) # Create a 10x10 array with values from 0 to 99
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
# Select the element at row 5, column 5 using nested list-style indexing
print(arr[5][5]) #try selecting different indices
# Or more concisely using comma-separated indices
print(arr[5,5])

55
55


### indexing with slicing

In [9]:
# Slice the array: rows 1 to 3 (exclusive), columns 4 to 6 (exclusive)
print(arr[1:3, 4:6])

[[14 15]
 [24 25]]


In [17]:
# Create a 4D array (2x2x2x2) and use ellipsis to slice the first dimension
arr = np.array(range(16))
print("arr: ", arr)

arr = arr.reshape(2,2,2,2)
print("reshaped arr: ", arr)

# Equivalent to arr[0,:,:,:]
print("arr[0, ...]: ", arr[0, ...])
print("arr[0,:,:,:]: ", arr[0,:,:,:]) #both give the same result, this one is used more often

arr:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
reshaped arr:  [[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
arr[0, ...]:  [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
arr[0,:,:,:]:  [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


### assign a scalar to a slice by broadcasting

In [ ]:
arr = np.array(range(100)).reshape((10,10)) # Create a 10x10 array with values from 0 to 99
arr[1:3,:] = 100    # set rows 1 and 2 to 100
arr[:,8:] = 100 # set last two columns to 100, all the rows
print(arr)

[[  0   1   2   3   4   5   6   7 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [ 30  31  32  33  34  35  36  37 100 100]
 [ 40  41  42  43  44  45  46  47 100 100]
 [ 50  51  52  53  54  55  56  57 100 100]
 [ 60  61  62  63  64  65  66  67 100 100]
 [ 70  71  72  73  74  75  76  77 100 100]
 [ 80  81  82  83  84  85  86  87 100 100]
 [ 90  91  92  93  94  95  96  97 100 100]]


### boolean indexing

In [20]:
arr1 = np.arange(25).reshape((5,5)) # 5x5 array
bools = np.array([True, True, False, True, False]) # boolean index array
print(arr1)
print("Boolean Indexing Result:")
print(arr1[bools])
print(arr1[bools].shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Boolean Indexing Result:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]
(3, 5)


In [21]:
print(arr1)
print("Boolean Negate Indexing Result:")
# negate the condition
print(arr1[~bools])    

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Boolean Negate Indexing Result:
[[10 11 12 13 14]
 [20 21 22 23 24]]


In [22]:
arr2 = np.array([1,2,3,4,5]) # sample array for condition-based indexing
# multiple conditions
print(arr2<2) # print boolean array where condition is met
print(arr2>4) # print boolean array where condition is met
print(arr1[(arr2<2) | (arr2>4)])    # select rows in arr1 where arr2 < 2 or arr2 > 4

[ True False False False False]
[False False False False  True]
[[ 0  1  2  3  4]
 [20 21 22 23 24]]


### fancy indexing

In [26]:
rs = np.random.RandomState(321) # create a random state object
arr = rs.rand(5,5)
print(arr)

[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]
 [0.4780419  0.09899468 0.27539478 0.79442731 0.51397031]
 [0.45329481 0.25515125 0.1139766  0.82431305 0.3177535 ]]


In [ ]:
# select arr[3,3], arr[1,2], arr[2,1]
print(arr[[3,1,2], [3,2,1]])        #this selects specific elements based on the provided row and column indices

[0.79442731 0.8840703  0.21229369]


### dimension inference

In [29]:
# dimension inference using any negative number (usually -1)
arr = np.array(range(16)) # 1D array with values from 0 to 15
print(arr)
print(arr.shape)
print(" ")
arr = arr.reshape((4,-1)) # reshape to 4 rows and infer columns
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)
 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(4, 4)


### find elements/indices by conditions

In [ ]:
arr = np.arange(16).reshape(4,4) # 4x4 array
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [31]:
# find the elements greater than 5 and return a flattened array
print(arr[arr>5])    # or arr[np.where(arr>5)]

[ 6  7  8  9 10 11 12 13 14 15]


In [32]:
# return values based on conditions 
# np.where(condition, true_return, false_return)
print(np.where(arr>5, -1, 10)) # if element > 5 return -1 else return 10

[[10 10 10 10]
 [10 10 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [33]:
# find the indices of the elements on conditions
print(np.argwhere(arr>5))

[[1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]


# Exercises

## Exercise 1: Reshaping Sensor Time-Series
**Goal:** Master the transition between "flat" data and structured "spatial-temporal" data.

**Scenario:** A water level sensor takes a reading every hour for 3 full days. You receive the data as a flat list of 72 readings.

* Create: Create a 1D array of 72 values representing water depth (you can use np.linspace(1.5, 5.0, 72) to simulate rising water).
* Reshape: Convert this 1D array into a 3D array with the shape (3, 24) to represent each day's values.
* Interpretation: Each row represents one day (3 total), and each column represents the hour of that day (24 total).
*  Use .shape to confirm the transformation and .transpose() to swap the axes so you have 24 rows and 3 columns.

In [2]:
# Create 1D array of 72 simulated water depth values
depth = np.linspace(1.5, 5.0, 72)

# Reshape into 3 days × 24 hours
depth_reshaped = depth.reshape(3, 24)

# Transpose to get 24 hours × 3 days
depth_transposed = depth_reshaped.transpose()

print("Original shape:", depth.shape)
print("Reshaped shape (days, hours):", depth_reshaped.shape)
print("Transposed shape (hours, days):", depth_transposed.shape)


Original shape: (72,)
Reshaped shape (days, hours): (3, 24)
Transposed shape (hours, days): (24, 3)


## Exercise 2: Accessing & Slicing Basin Grids
**Goal:** Extract specific geographical data from a 2D spatial grid.

**Scenario:** You have a $5 \times 5$ grid representing soil moisture percentages across a local watershed.

```
moisture_grid = np.array([
    [32, 35, 30, 28, 25],
    [40, 42, 38, 35, 30],
    [55, 58, 52, 48, 42],
    [60, 65, 62, 58, 55],
    [70, 72, 70, 68, 65]
])
```

* Index: Access the soil moisture at the dead center of the grid (row 2, column 2).
* Slice: Extract a "sub-basin" consisting of the top-left $3 \times 3$ corner.
* Slicing Columns: Extract the moisture levels for the entire 4th column (index 3), representing a North-South transect of the area.


In [3]:
moisture_grid = np.array([
    [32, 35, 30, 28, 25],
    [40, 42, 38, 35, 30],
    [55, 58, 52, 48, 42],
    [60, 65, 62, 58, 55],
    [70, 72, 70, 68, 65]
])

# Center value (row 2, column 2)
center_value = moisture_grid[2, 2]

# Top-left 3x3 sub-basin
sub_basin = moisture_grid[:3, :3]

# Entire 4th column (index 3)
column_4 = moisture_grid[:, 3]

print("Center value:", center_value)
print("Top-left 3x3 sub-basin:\n", sub_basin)
print("4th column (index 3):", column_4)


Center value: 52
Top-left 3x3 sub-basin:
 [[32 35 30]
 [40 42 38]
 [55 58 52]]
4th column (index 3): [28 35 48 58 68]


## Exercise 3: Advanced Filtering (Broadcasting & Fancy Indexing)

**Goal:** Use conditional logic and specific indices to identify weather anomalies.

**Scenario:** You have a 1D array of daily rainfall in mm: rain = np.array([0, 0, 12.5, 45.0, 5.2, 0, 18.9, 31.2, 0, 2.1]).

* Broadcasting: Convert the entire array from millimeters to inches (1 mm $\approx$ 0.039 inches) using a single broadcasted operation.

* Boolean Indexing: Create a new array called heavy_rain that contains only the values from the original rain array that are greater than 20 mm.

* Finding Elements: Use np.where() to find the indices of all days where rainfall was exactly 0.

* Fancy Indexing: You are told that sensors at indices [2, 3, 6] are the most reliable. Use a list of these indices to extract those specific values from the rain array.

In [4]:
rain = np.array([0, 0, 12.5, 45.0, 5.2, 0, 18.9, 31.2, 0, 2.1])

# Convert mm to inches using broadcasting
rain_inches = rain * 0.039

# Boolean indexing: rainfall > 20 mm
heavy_rain = rain[rain > 20]

# Indices where rainfall is exactly 0
zero_rain_days = np.where(rain == 0)

# Fancy indexing: extract reliable sensor readings
reliable_indices = [2, 3, 6]
reliable_readings = rain[reliable_indices]

print("Rain in inches:", rain_inches)
print("Heavy rain (>20 mm):", heavy_rain)
print("Indices with zero rainfall:", zero_rain_days)
print("Reliable sensor readings:", reliable_readings)


Rain in inches: [0.     0.     0.4875 1.755  0.2028 0.     0.7371 1.2168 0.     0.0819]
Heavy rain (>20 mm): [45.  31.2]
Indices with zero rainfall: (array([0, 1, 5, 8]),)
Reliable sensor readings: [12.5 45.  18.9]


Next [Module](./8.%20Combine%20&%20Split%20an%20Array.ipynb)